version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.1
    container_name: broker
    depends_on:
      - zookeeper
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
    #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    #   KAFKA_JMX_PORT: 9101
    #   KAFKA_JMX_HOSTNAME: localhost

#   schema-registry:
#     image: confluentinc/cp-schema-registry:6.1.1
#     container_name: schema-registry
#     depends_on:
#       - broker
#     network_mode: host
#     environment:
#       SCHEMA_REGISTRY_HOST_NAME: localhost
#       SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: localhost:29092
#       SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

#   connect:
#     image: cnfldemos/kafka-connect-datagen:0.4.0-6.1.0
#     container_name: connect
#     depends_on:
#       - broker
#       - schema-registry
#     network_mode: host
#     environment:
#       CONNECT_BOOTSTRAP_SERVERS: localhost:29092
#       CONNECT_REST_ADVERTISED_HOST_NAME: localhost
#       CONNECT_REST_PORT: 8083
#       CONNECT_GROUP_ID: compose-connect-group
#       CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
#       CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#       CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
#       CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
#       CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#       CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
#       CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#       CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
#       CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
#       CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://localhost:8081
#       CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
#       CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR